name: unit tests

on: 
  push:
    branches:
      - '*'

permissions:
    checks: write
    
jobs:
  build:
    name: test
    runs-on: runner
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: |
         npm install chart.js chartjs-node-canvas

      - name: Install cmake
        run: |
          brew install cmake
          cmake --version
                   
      - name: build tests
        run: |
         cd projects
         cmake -B build -S .
         cmake --build build
         pwd
         cd build
         ctest -C checkin --output-junit unittest.xml
         ls -la
         
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/*.xml'
          summary: |
           Unit Tests Summary - Complete
           
      - name: Generate Unit Test Summary
        id: summary
        run: |
          echo "const { Chart } = require('chart.js');" > summary.js
          echo "const { createCanvas } = require('canvas');" >> summary.js
          echo "const passedTests = 10;" >> summary.js
          echo "const failedTests = 5;" >> summary.js
          echo "const canvas = createCanvas(800, 600);" >> summary.js
          echo "const ctx = canvas.getContext('2d');" >> summary.js
          echo "const chart = new Chart(ctx, {" >> summary.js
          echo "  type: 'pie'," >> summary.js
          echo "  data: {" >> summary.js
          echo "    labels: ['Passed', 'Failed']," >> summary.js
          echo "    datasets: [{" >> summary.js
          echo "      data: [passedTests, failedTests]," >> summary.js
          echo "      backgroundColor: ['#36A2EB', '#FF6384']," >> summary.js
          echo "      hoverBackgroundColor: ['#36A2EB', '#FF6384']" >> summary.js
          echo "    }]" >> summary.js
          echo "  }," >> summary.js
          echo "  options: {" >> summary.js
          echo "    plugins: {" >> summary.js
          echo "      legend: {" >> summary.js
          echo "        position: 'bottom'" >> summary.js
          echo "      }" >> summary.js
          echo "    }" >> summary.js
          echo "  }" >> summary.js
          echo "});" >> summary.js
          echo "const svg = chart.toBase64Image();" >> summary.js
          echo "require('fs').writeFileSync('chart.svg', svg, 'base64');" >> summary.js
          node summary.js
          
      - name: Attach Pie Chart
        uses: actions/upload-artifact@v2
        with:
          name: Pie Chart
          path: chart.svg
         

