name: unit tests

on: 
  push:
    branches:
      - '*'

jobs:
  build:
    name: test
    runs-on: runner
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3
        
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.8.0

      - name: current directory
        run: pwd

      - name: Install cmake
        run: |
          brew install cmake
          cmake --version
                   
      - name: build tests
        run: |
         cd projects
         cmake -B build -S .
         cmake --build build
         pwd
         cd build
         ctest -C checkin --output-junit unittest.xml
         
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: |
            **/*.xml
         

