name: unit tests

on:
  push:
    branches:
      - "*"

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build:
    name: test
    runs-on: runner
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3

      - name: Install cmake
        run: |
          brew install cmake
          cmake --version
          
      - name: Debug Git Log
        run: |
          # Fetch the base repository's commit history
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git log --oneline ${{ github.event.pull_request.base.sha }}..${{ github.sha }}

      - name: Get Modified Files
        id: files
        run: |
          git diff --name-only ${{ github.base_ref }} ${{ github.sha }}
          
      - name: Print Edited Files
        run: |
          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr_${{ github.event.pull_request.number }}
          git diff pr_${{ github.event.pull_request.number }} --name-only

      - name: build tests
        run: |

         cd projects
         cmake -B build -S .
         cmake --build build
         pwd
         cd build
         ctest -C checkin --output-junit unittest.xml
         ls -la
          
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: |
            **/*.xml
