name: unit tests

on:
  push:
    branches:
      - "*"

permissions:
  checks: write

jobs:
  build:
    name: test
    runs-on: runner
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3

      - name: current directory
        run: pwd

      - name: Install cmake
        run: |
          brew install cmake
          cmake --version

      - name: build tests
        run: |
          cd projects
          cmake -B build -S .
          cmake --build build
          pwd
          cd build
          ctest -C checkin --output-junit unittest.xml
          ls -la

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: "**/*.xml"
          
      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        if: always() # always run even if the previous step fails
        with:
          name: junit-test-results
          path: '**/*.xml'
          retention-days: 1
          
---
name: report
on:
  workflow_run:
    workflows: [unit tests]
    types: [completed]
    
permissions:
  checks: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Download Test Report
        uses: dawidd6/action-download-artifact@v2
        with:
          name: junit-test-results
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          commit: ${{github.event.workflow_run.head_sha}}
          report_paths: '**/*.xml'
