name: unit tests

on: 
  push:
    branches:
      - '*'

permissions:
    checks: write
    
jobs:
  build:
    name: test
    runs-on: runner
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3

      - name: current directory
        run: pwd

      - name: Install cmake
        run: |
          brew install cmake
          cmake --version
                   
      - name: build tests
        run: |
         cd projects
         cmake -B build -S .
         cmake --build build
         pwd
         cd build
         ctest -C checkin --output-junit unittest.xml
         ls -la
         
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/*.xml'
          summary: |
           Unit Tests Summary - Complete
           
      - name: Generate Unit Test Summary
        id: summary
        run: |
          # Calculate your test result numbers
          passed_tests=10
          failed_tests=5
          total_tests=$((passed_tests + failed_tests))
          
          # Create a pie chart using GitHub Script
          echo "::set-output name=chart::$(echo "Passed=$passed_tests,Failed=$failed_tests" | base64)"

      - name: Display Pie Chart
        uses: technote-space/github-action-bar@v2
        with:
          chart: ${{ steps.summary.outputs.chart }}
         

