name: unit tests


on:
  pull_request:
    types: [opened, synchronize, reopened]


# adding permissions to workflow to allow writing to status
permissions:
  contents: read
  checks: write
  pull-requests: write


jobs:
  build:
    name: test
    runs-on: runner
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3
        with:
         fetch-depth: 2


      - name: Install cmake
        run: |
          brew install cmake
          cmake --version


      - name: List Modified Files
        run: |
          # List the names of the modified files in the pull request - open a pull request
          set -x
          git --version
          files_edited=$(git diff --name-only ${{ github.event.pull_request.base.sha }}...${{ github.sha }})
          # Replace newline characters with spaces
          files_edited="${files_edited//$'\n'/ }"
          echo "FILES=${files_edited}" >> $GITHUB_ENV
          
          
      - name: print files
        run: |
          IFS=' ' read -ra FILES_TO_READ <<< "$FILES"
          
          echo "$FILES"
          echo "--------------------------"
          
          for f in ${FILES_TO_READ[@]}; do
           echo "$f"
          done


      - name: build tests
        run: |

         cd projects
         cmake -B build -S .
         cmake --build build
         pwd
         cd build
         ctest -C checkin --output-junit unittest.xml
         ls -la
          
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: |
            **/*.xml
            
      - name: Set Variable
        id: set_variable
        run: echo "my_variable=10" >> $GITHUB_ENV # Replace '10' with the actual value from your workflow

      - name: Generate Badge URL
        id: generate_badge
        run: |
          my_variable=${{ steps.set_variable.outputs.my_variable }}
          badge_url=$(curl -s "https://img.shields.io/badge/YOUR_BADGE_LABEL-$my_variable-blue") # Replace 'YOUR_BADGE_LABEL' with the desired label for your badge
          echo "badge_url=$badge_url" >> $GITHUB_ENV

      - name: Print Badge URL
        run: echo "Badge URL:${{ steps.generate_badge.outputs.badge_url }}"

      - name: Replace Badge URL in Markdown
        run: |
          badge_url="${{ steps.generate_badge.outputs.badge_url }}"
          sed -i "s|badge_url_from_workflow|$badge_url|g" README.md
